#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# ARG BUILD_CONFIGURATION=Release
WORKDIR .
RUN mkdir /app
COPY ./ /app
WORKDIR /app

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG DB_IP


RUN sed -ir "s/Server=[^;]*;/Server=$DB_IP;/g" ./appsettings.json
RUN sed -ir "s/User=[^;]*;/User=$MYSQL_USER;/g" ./appsettings.json
RUN sed -ir "s/Password=[^;]*;/Password=$MYSQL_PASSWORD;/g" ./appsettings.json


RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

# RUN rm -rf Migrations/*
# RUN dotnet ef migrations add InitialCreate -c ThesisDbContext
RUN sed -i 's/\r//g' ./migrate.sh
# CMD ["./migrate.sh"]
CMD [ "bash","./migrate.sh"]