x-mariadb-common: &mariadb-common
  build:
    context: .
    dockerfile: ./Dockerfile_db
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
  restart: unless-stopped
  healthcheck:
    test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
    start_period: 1m
    start_interval: 10s
    interval: 1m
    timeout: 5s
    retries: 3
  networks:
    - thesis-internal-network




services:
  mariadb-prod:
    <<: *mariadb-common  # Same config as 'mariadb'
    volumes:
      - ./data/db/:/var/lib/mysql/
    profiles:
      - prod

  mariadb-dev:
    <<: *mariadb-common  # Same config as 'mariadb'
    profiles:
      - dev  # Only runs in the 'dev' profile
      - only-db
    ports:
      - "3306:3306"  # Exposes port only in 'dev' profile

  thesis:
    tty: true
    stdin_open: true
    build:
      dockerfile: Dockerfile
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - DB_IP=mariadb-prod
    ports:
      - "8000:8000"
    volumes:
      - ./data/backend_data:/home/app/Data
      - ./data/temp/certs:/app/certs/:rw
    environment:
      - GRAYLOG_IP=${GRAYLOG_IP}
      - GRAYLOG_PORT=${GRAYLOG_PORT}
      - DOMAIN=${DOMAIN}
      - ASPNETCORE_URLS=http://*:8000
    restart: unless-stopped
    profiles:
      - prod
    depends_on:
      mariadb-prod:
        condition: service_healthy
    networks:
      - thesis-internal-network

networks:
  thesis-internal-network:
    driver: bridge
