FROM mariadb:11.4.2-noble

RUN apt-get update && apt-get install -y dos2unix && rm -rf /var/lib/apt/lists/*

COPY ./docker/db_init.sh /docker-entrypoint-initdb.d/init.sh

RUN dos2unix /docker-entrypoint-initdb.d/init.sh
RUN chmod -R 777 /docker-entrypoint-initdb.d/init.sh