// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thesis_backend.Data_Structures;

#nullable disable

namespace Thesis_backend.Migrations
{
    [DbContext(typeof(ThesisDbContext))]
    [Migration("20240720164202_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Thesis_backend.Data_Structures.Game", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("Currency")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("CurrentXP")
                        .HasColumnType("bigint");

                    b.Property<int>("Lvl")
                        .HasColumnType("int");

                    b.Property<int>("NextLVLXP")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("GamesTable");
                });

            modelBuilder.Entity("Thesis_backend.Data_Structures.Task", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastCompleted")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PeriodRate")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TaskOwner")
                        .HasColumnType("bigint");

                    b.Property<bool>("completed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("TasksTable");
                });

            modelBuilder.Entity("Thesis_backend.Data_Structures.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastLoggedIn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Registered")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("SettingsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("Username", "Email")
                        .IsUnique();

                    b.ToTable("UsersTable");
                });

            modelBuilder.Entity("Thesis_backend.Data_Structures.UserSettings", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("ProfilePic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("privacy")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("UserSettingsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
